name: Intake

on:
  push:
    branches: [ tpl-intake ]
    paths: [ tpl-*.toml ]

jobs:
  New-Submission:
    if: "startsWith(github.event.head_commit.message, 'Merge pull request')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Extract the new template ID and OSF project
      run: |
        HEAD_BRANCH=$( git log -m -1 --name-only | grep "Merge pull" | sed 's+^ *Merge pull request #[0-9]* from .*/pr/++g' )
        if [[ "$HEAD_BRANCH" == "" ]]; then
          echo "ERROR: could not parse the head branch of merge commit."
          exit 1
        fi
        echo "Starting intake of ${HEAD_BRANCH}"
        TEMPLATE_ID=${HEAD_BRANCH#*/}
        OSF_PROJECT=${HEAD_BRANCH%/*}

        echo "TEMPLATE_ID=${TEMPLATE_ID}" >> ${GITHUB_ENV}
    - name: "Run intake action"
      uses: templateflow/actions-intake@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.NIPREPS_BOT }}
        GITHUB_USER: nipreps-bot
        GITHUB_TOKEN: ${{ secrets.NIPREPS_BOT_PAT }}
        DATALAD_github_token: ${{ secrets.NIPREPS_BOT_PAT }}
        OSF_PASSWORD: ${{ secrets.OSF_PASSWORD }}
        OSF_USERNAME: ${{ secrets.OSF_USERNAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GIN_TOKEN: ${{ secrets.GIN_TOKEN }}

